- configTools/src/main/scala/com/gu/janus/policy/Statements.scala
- configTools/src/test/scala/com/gu/janus/policy/StatementsTest.scala
- example/build.sbt
- example/src/main/scala/com/example/Data.scala
Move Statements out of example and into configTools, and bump the version of configTools depended upon.
The Statements are a useful shared functionality that can be used for creating bespoke policies.
This also adds the required `permissionsRepo` to the JanusData used in the example app.
We can release a new version of configTools
> Move statements into configTools

- app/conf/Config.scala
- app/logic/AuditTrail.scala
- build.sbt
- configTools/src/test/scala/com/gu/janus/JanusConfigTest.scala
- configTools/src/test/scala/com/gu/janus/ValidationTest.scala
- configTools/src/test/scala/com/gu/janus/config/ConfigIntegrationTests.scala
- configTools/src/test/scala/com/gu/janus/config/LoaderTest.scala
- configTools/src/test/scala/com/gu/janus/config/WriterTest.scala
- configTools/src/test/scala/com/gu/janus/policy/StatementsTest.scala
- configTools/src/test/scala/com/gu/janus/testutils/HaveMatchers.scala
- configTools/src/test/scala/com/gu/janus/testutils/RightValues.scala
- project/plugins.sbt
- test/aws/AuditTrailDBTest.scala
- test/aws/FederationTest.scala
- test/conf/ConfigTest.scala
- test/instances/ACLMergeTest.scala
- test/logic/AccountOrderingTest.scala
- test/logic/AuditTrailTest.scala
- test/logic/CustomisationTest.scala
- test/logic/DateTest.scala
- test/logic/FavouritesTest.scala
- test/logic/OwnersTest.scala
- test/logic/PlayHelpersTest.scala
- test/logic/RevocationTest.scala
- test/logic/UserAccessTest.scala
- test/logic/ViewHelpersTest.scala
Update library dependencies, particularly the Play Googleauth dependency so that we take advantage of [an important security fix from the Google Auth library](https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEOAUTHCLIENT-575276).
Up-to date software without security problems, with the application still working as expected.
A separate PR will follow to update the way Play-Googleauth is used, for now the deprecated constructors are still being called. To prevent this causing compile errors, the PR also bumps the project to Scala 2.13.x so we get the `@nowarn` annotation. This change meant quite a few dependencies needed updating and it spiralled from there.
Of note, is that `scalatest` moved a few things around with v3.2 so the test changes are quite verbose. For the most part it is just renaming, …
> Update versions of Scala and library dependencies

- configTools/src/main/scala/com/gu/janus/VerifyJanusData.scala
Add support for verification that the JanusData can be found and loaded.
This can be ran as part of a build script and will provide helpful information if an error is encountered and prevent the build from continuing.
Janus will only be deployed if the janusData is present and valid. 
Example of error printed before a non-zero exit:
> Add method to verify the janusData can be found and loaded

- configTools/version.sbt
Version 0.0.5 of configTools is [now available](https://mvnrepository.com/artifact/com.gu/janus-config-tools_2.13/0.0.5) on mvnrepository. This updates the version of configTools to reflect the current release.
It not possible possible for the sbt release plugin to push updates to master because this Git repository is locked-down. After performing the release, it is necessary to raise a PR to share the updated version number. 🚀 🌕
> Update version number of configTools

- README.md
Expand the README how to update the version number of configTools in the main branch after publishing a release.
Ensure someone following the readme switches the the correct project before attempting to release configTools.
Encourage pushing git tags along with branch to the remote so that releases of configTools are tagged.
> Add more details on how to publish configTools

- conf/logback.xml
* This change allows us to send logs to `stdout` as well as a log file. This allows us to collect logs via [Fluent Bit's systemd plugin](https://docs.fluentbit.io/manual/pipeline/inputs/systemd), which is an approach we're exploring for shipping logs at the OS level (rather than via changes to the application code).
* Application logs should be available via `journalctl -u janus.service`
* When combined with the [config added here](https://github.com/guardian/janus/pull/2774), we should be able to ship logs to Central ELK
> Add console logging

- .bsp/sbt.json
- app/AppComponents.scala
- app/conf/Config.scala
- app/controllers/AuthController.scala
- app/controllers/Janus.scala
- build.sbt
- configTools/version.sbt
- project/build.properties
- project/plugins.sbt
Immediate motivation was to use the dependencyTree command to check for Log4j usage (re recent security vulnerability). But this is generally useful in any case.
See also: https://github.com/guardian/janus/pull/2904.
(Not really tested beyond CI - any suggestions on best way to test this appreciated.)
**Note: the Play upgrade would ideally be in a separate PR, but is forced by https://github.com/guardian/ophan/commit/bf8576e5c3a3c813de8b64271d3db260c7befbdf.**
> Upgrade SBT to 1.5.6 (edit to 1.5.7 and Play from 2.7 to 2.8)

- build.sbt
- conf/logback.xml
Following #21 (and as [commented upon](https://github.com/guardian/janus-app/pull/21#discussion_r693978977)), this change uses the Logstash Encoder to output logs in JSON format. These are easier to consume by machines, in this case Fluentbit via [devx-logs](https://github.com/guardian/devx-logs).
Regarding the jackson overrides, this is to address compatibility issues with the version of the logstash encoder and Play and also addresses a vulnerability. See https://github.com/orgs/playframework/discussions/11222. See https://github.com/guardian/amiable/pull/133 for similar.
In conjunction with https://github.com/guardian/janus/pull/3050, this change means our infrastructure becomes simpler as we've fewer configuration files.
This will close #22.
> fix: Write logs to console in JSON format

- .github/workflows/dep-updates_pr-tracking-branch-to-default.yml
- .github/workflows/dep-updates_set-automerge.yml
- .github/workflows/dep-updates_tracking-branch.yml
Adds a series of github actions workflows, which combine to create a process for addressing dependency updates from an automated tool (e.g. Scala Steward). PRs from those tools will target a branch that tracks main, and every month (1st day of the month) a batch-PR will be created targeting main. This reduces the overhead of reviewing/testing dependency updates.
> chore: Add dependency update batching workflows

- README.md
- app/AppComponents.scala
- app/conf/Config.scala
This enables a better setup experience for users trying to run Janus locally, by allowing the Janus data file generated by a separate project to be referred to outside of the resources folder when doing local development.
See https://github.com/guardian/janus/pull/3273 for how this change is used.
**Next steps:** Following merging the above referenced PR, we should update the documentation in this repository to point Guardian engineers trying to run the Guardian version of Janus to the private Janus repo.
> Allow janusData to be pulled from a file outside resources

- README.md
This is a small documentation update to point at the docs for guardian engineers to get started quickly.
Follows https://github.com/guardian/janus/pull/3273
> Add a pointer to the docs for Guardian engineers

- example/build.sbt
- example/src/main/scala/com/example/Access.scala
The example project here was being flagged by vulnerability monitoring, also upon inspection it did not appear to compile / test successfully.
This change bumps some dependencies in the example project to provide better defaults for someone using the project and removes some code that was preventing the project compiling.
> Bump dependencies on example project

- .github/workflows/snyk.yml
This repo includes an example project that is not used for anything in production. This change excludes that directory from the scan
These vulnerabilities are not ones we are concerned about, excluding them makes our count go down
Dependency patches will still be applied by scala steward, but are less critical as the example project is not used.
> exclude test project from snyk scan

- .github/workflows/trigger-private-janus-build.yml
This change removes the `janus-app-branch` input to the Workflow being triggered in `guardian/janus`, removing an edge case where feature branches were being deployed to PROD.
The build is now:
1. Compile the Scala app, and run the tests
2. If compilation is successful, and we're on the `main` branch, trigger the Workflow in `guardian/janus`
3. The Workflow in `guardian/janus` will clone always clone the main branch of this repository
With these changes we lose the ability to deploy feature branches (as their build will not appear in Riff-Raff), however looking at the deployment history, this isn't a thing we've ever done.
These changes removes an edge case from the build where feature branches in this repository were being deployed to PROD.
Here's a diagram of the build steps:
---
See …
> ci: Tighten the build

- build.sbt
- project/plugins.sbt
https://github.com/guardian/sbt-riffraff-artifact is deprecated, and also unused as https://github.com/guardian/janus has adopted https://github.com/guardian/actions-riff-raff.
Fewer dependencies.
N/A.
N/A.
> chore(deps): Remove `sbt-riffraff-artifact`

- .github/workflows/trigger-private-janus-build.yml
- build.sbt
Reverts guardian/janus-app#379
The upgrade to Java 11 has not worked and I don't have time to fix forwards at the moment, so reverting for now.
https://github.com/guardian/janus/pull/3896 should also be merged to revert this upgrade.
> Revert "chore: Move to Java 11"

- .github/workflows/trigger-private-janus-build.yml
- build.sbt
This is a re-attempt to upgrade Java to v11. This was attempted in #379 and reverted in #381.
Requires: https://github.com/guardian/janus/pull/3947 which should be merged first, as Java 11 is backwards compatible with Java 8.
> chore: Upgrade to Java 11

- .github/workflows/trigger-private-janus-build.yml
We missed this in #396.
---
Co-authored-by: @tjsilver
> ci: Get a GitHub token before checking status

- configTools/version.sbt
This bumps the version of `janus-config-tools` to v0.0.6. This reflects the version of the latest Maven release.  
The published version has its dependency updates and the versions are in line between Maven and this repo.
Co-authored-by: @adamnfish
> Chore: bump config tools after releasing to Maven

- .github/workflows/dependency-graph.yml
Adds a workflow that updates the dependency graph with SBT dependencies, using the third party (from Scalacenter) [SBT Dependency Submission workflow](https://github.com/marketplace/actions/sbt-dependency-submission).
This wil allow Dependabot to report on vulnerabilites in Scala dependencies. 
This has been tested on push to this branch and [created a snapshot of the dependencies](https://api.github.com/repos/guardian/janus-app/dependency-graph/snapshots/10509078). (See them under `snapshots > manifests > com.gu:janus... > resolved`).
When it is run on `main` after this PR is merged, the Scala dependencies should appear in [the dependency graph in this repo](https://github.com/guardian/janus-app/network/dependencies).
> feat: add sbt dependency submission action

- project/plugins.sbt
Adds the SBT dependency tree plugin.
This will allow us to generate the dependency tree locally, including using the useful `dependencyBrowseTree` command to display a searchable tree in the browser.
> chore: add dependency tree plugin

- build.sbt
Makes the configTools project use the same version of `jackson-databind` as the main app. 
This is an attempt to mitigate the critical issues discovered by Dependabot, whereby configTools' reliance on [aws-scala](https://github.com/seratch/AWScala) which has been deprecated, and which in turn relies on an old version of `jackson-databind` (v2.6). Once this is merged, if successful we should see the critical issues disappear.
I have tested this locally and the dependency tree for configTools shows that the vulnerable v2.6 is now evicted by the safe version:
> use later jackson-databind version in configTools

- build.sbt
Makes the configTools project use the same version of `aws-sdk` as the main app. 
This is an attempt to mitigate a high severity vulnerability discovered by Dependabot, whereby configTools' reliance on [aws-scala](https://github.com/seratch/AWScala) which has been deprecated, and which in turn relies on an old version of `aws-java-sdk-s3`. Once this is merged, if successful we should see the issue disappear.
I have tested this locally and the dependency tree for configTools shows that the vulnerable version has been replaced a safe version:
Before: 
After:
> fix: use later aws sdk version in configTools

- build.sbt
This [fixes](https://github.com/guardian/play-googleauth/pull/218) an issue with the `locale` field in Google's response.
The observed error is:
```log
play.api.libs.json.JsResultException: JsResultException(errors:List((/locale,List(JsonValidationError(List(error.path.missing),List())))))
at play.api.libs.json.JsReadable.$anonfun$as$2(JsReadable.scala:25)
at play.api.libs.json.JsError.fold(JsResult.scala:66)
at play.api.libs.json.JsReadable.as(JsReadable.scala:24)
at play.api.libs.json.JsReadable.as$(JsReadable.scala:23)
at play.api.libs.json.JsObject.as(JsValue.scala:116)
at com.gu.googleauth.UserInfo$.fromJson(model.scala:41)
at com.gu.googleauth.GoogleAuth$.$anonfun$validatedUserIdentity$6(auth.scala:242)
at com.gu.googleauth.GoogleAuth$.googleResponse(auth.scala:182)
at …
```
> chore(deps): Update play-googleauth to v4.0.0

- .github/dependabot.yml
Adds Dependabot version updates to GitHub Actions. 
We are now using commit SHAs as action versions (since PR #417) and this will allow them to be kept up to date with Dependabot.
> feat: dependabot version updates for github actions

- README.md
Updates the README with more information about publishing the Janus ConfigTools.
> docs: update readme with link

- .github/workflows/trigger-private-janus-build.yml
Make sure that the build for this repository correctly reports success or failure.
The real build gets kicked off in another repository, and then we have a step that waits for a while before checking if it succeeded. In practice, with a cold cache we observe that a 6 minute wait covers all cases, so we've upped the wait time.
Note: Better would be to poll until the build completes, but since this doesn't actually delay anything, no harm in having it be long enough that it reliably gives the correct answer.
> Increase the time we wait for the private build to complete

- app/views/main.scala.html
- conf/routes
The default WAF rules block URLs that look like important endpoints (e.g. /admin).
Allow access to the superuser endpoints for InfoSec.
We should be able to access this endpoint, behind the WAF.
> Change `/admin` to `/superuser` to avoid the WAF

- .gitignore
- .tool-versions
- build.sbt
See https://github.com/guardian/gha-scala-library-release-workflow/pull/36 - [`gha-scala-library-release-workflow`](https://github.com/guardian/gha-scala-library-release-workflow) has moved to _requiring_ projects to specify what version of Java they want to use to build, and this is expressed through an [`asdf`](https://asdf-vm.com/)-formatted `.tool-versions` file.
This allows individual projects to experiment with later (or even _earlier_) versions of Java if they wish, without requiring all other projects using `gha-scala-library-release-workflow` to upgrade their version of Java at the same time.
Note that, although this PR specifies Java 21 (the latest LTS release of Java, which apparently has several performance benefits) for the library _build_, the artifacts released by the …
> Add Java version - see guardian/gha-scala-library-release-workflow#36

- .github/workflows/trigger-private-janus-build.yml
- app/views/index.scala.html
- conf/application.conf
- public/javascripts/janus.js
- public/stylesheets/main.css
When working with multiple AWS accounts throughout the day, it would be useful to have an (optional) auto-logout feature when clicking through to the console of the next/desired AWS account.
Turns out there's already an issue for this from 2017: https://github.com/guardian/janus/issues/868
- allow `signin.aws.amazon.com` and `aws.amazon.com` as `connect-src`s in the CSP in anticipation of calling it client-side to perform auto-logout
- add an 'Auto-logout' toggle (persisted to local storage) and if active silently hit `https://signin.aws.amazon.com/logout` for AWS Console links before redirecting to the AWS console for desired/clicked account (gives up after 1.5s and redirects regardless)
> add auto-logout toggle

- app/aws/Federation.scala
- app/controllers/Janus.scala
- app/logic/Customisation.scala
- app/views/index.scala.html
- public/javascripts/janus.js
- public/stylesheets/main.css
- test/aws/FederationTest.scala
This PR is an augmentation of the following. Unfortunately, this one is in a fork I do not have access to, so I've had to raise a duplicate PR and close that one.
https://github.com/guardian/janus-app/pull/448
Copying the information from that PR, with thanks to @twrichards:
------------------
Looking to achieve the same as #439 and #447 were trying to do, but achieving it server-side, if toggle is active (persisted via cookie now, so server can see the preference on the request) [for AWS Console buttons] the server redirects to `https://us-east-1.signin.aws.amazon.com/oauth?Action=logout` with a `redirect_uri` query param containing the federated login link Janus would normally redirect to directly (see https://serverfault.com/a/1097528).
**✅ TESTED the logout with `redirect_uri` …
> Auto logout support for console URLs

- .github/workflows/dependency-graph.yml
- .github/workflows/trigger-private-janus-build.yml
- installs sbt in the build workflow
- installs java and sbt in the dependency submission workflow and updates it to reflect how the dependency graph integrator-raised PRs look.
Ubuntu latest no longer includes sbt, so it needs to be installed explicitly.
Tested the dependency submission action [before](https://github.com/guardian/janus-app/actions/runs/11210047264) and [after](https://github.com/guardian/janus-app/actions/runs/11347263637). The build action [failed on this pr](https://github.com/guardian/janus-app/actions/runs/11347333410) until the [commit to add sbt](https://github.com/guardian/janus-app/actions/runs/11347406629) was made.
> fix: explicitly install java/sbt in build and dependency submission workflow

- app/AppComponents.scala
- app/aws/Clients.scala
- test/aws/AuditTrailDBTest.scala
Fixes the database when running the application locally.
The helper library being used for DB access is not compatible with recent versions of DynamoDB loal. DynamoDB now verifies that access credentials have the right format, even for local development where they are not actually used. The library was using empty strings for the access key and secret, which did not pass validation.
This PR adds a utility for creating a valid DynamoDB client for local use, which is consumed from the server itself (in DEV mode) and the database integration tests.
Unfortunately, the code that sets up the local DB client also uses a deprecated method, so we suppress this deprecation warning for now. Fixing this properly will mean moving off AWScala, a job that we already know about.
> Fix the DB for local development

- .github/workflows/dependency-graph.yml
For some reason the GHA workflow version comment did not get properly updated in https://github.com/guardian/janus-app/pull/484.
> Fix the GHA workflow version comment

- configTools/src/main/scala/com/gu/janus/model/models.scala
When people set up a new AWS account in Janus it helps if people clearly understand what these fields are for. Because the `authConfigKey` field has multiple purposes, it helps to make this clear to the reader.
It should be easier for people to onboard new AWS accounts in the future.
Replaces https://github.com/guardian/janus-app/pull/479 in a fork that the current DevX/Security team members control.
> Document the AWS Account model fields

- .github/workflows/dependency-graph.yml
- .github/workflows/trigger-private-janus-build.yml
- .tool-versions
This workflow installs Java and sbt, and is managed by us. Also updates the .tool-versions file, which was pointing at an out-of-date version of Java. We now only specify the major Java version, which is supported locally by `mise` (but not `asdf`).
> Switch to guardian/setup-scala in GHA workflows

- app/AppComponents.scala
- app/aws/AuditTrailDB.scala
- app/aws/Clients.scala
- app/aws/DynamoDB.scala
- app/controllers/Audit.scala
- app/controllers/Janus.scala
- app/logic/AuditTrail.scala
- build.sbt
- test/aws/AuditTrailDBTest.scala
- test/logic/AuditTrailTest.scala
To remove the deprecated AWS v1 Dynamo DB client and replace it with v2.
This is very difficult to do without also removing the awscala Dynamo DB library, which depends on the AWS v1 client.
Code is up to date and easier to patch in future.
Should still be able to:
* search the audit page
* see the audit page updating
> Remove v1 AWS dynamodb client and awscala dynamo lib

- app/aws/Federation.scala
- app/controllers/Janus.scala
- app/logic/Customisation.scala
- app/views/index.scala.html
- public/javascripts/janus.js
- public/stylesheets/main.css
- test/aws/FederationTest.scala
Makes Janus compatible with the new multi-login support in the AWS console. The existing logout (and auto-logout) functionality exists to support users' ability to easily switch between AWS accounts with Janus, but the ability to crteate multiple concurrent AWS console logins means this is no longer required.
We now encourage users to turn on AWS' multi-session support, and remove the now redundant (and broken) login functionality from Janus. Users obtain AWS access from Janus as before, and can now manage their sessions directly from the AWS console via the drop-down at the top right.
Our colleagues will be able to use Janus to seamlessly log into multiple AWS accounts.
This shows how to enable multi-session support in the AWS console, using the drop-down in the top right of the AWS …
> Remove logout to support aws multiple console sessions

- app/aws/Clients.scala
- app/aws/Federation.scala
- app/controllers/Janus.scala
- app/controllers/RevokePermissions.scala
- app/logic/Date.scala
- app/logic/ViewHelpers.scala
- app/views/consoleUrl.scala.html
- app/views/credentials.scala.html
- build.sbt
- test/logic/ViewHelpersTest.scala
To remove the deprecated AWS v1 STS client and replace it with v2.  
And to remove the awscala STS library which has a dependence on the v1 client.
Code is up to date and easier to patch in future.
Should still be able to:
* get temporary credentials to sign in to the AWS console
* get temporary credentials to access AWS locally
* have temporary credentials that expire at the expected time
* revoke access to an account for credentials created before a threshold datetime
This is part of a series of PRs to upgrade AWS clients to v2.
See also:
* #500
> Upgrade AWS STS client to v2

- app/aws/Clients.scala
The region for the AWS Java STS client was being read from the local users' config but this can't be relied on.
So now setting it explicitly in the code.
> Set AWS STS client's region explicitly

- .github/workflows/trigger-private-janus-build.yml
- frontend/package-lock.json
- frontend/package.json
Adds an NPM step to the CI to install and build node dependencies. For the moment, `npm run build` only echoes out a message, but when #512  is implemented, it will run the parcel build for the frontend app.
This will allow us to ensure that when #512  is merged, the CI is in place to successfully deploy the frontend build.
This PR will need to be merged ahead of the [related PR in the janus repo](https://github.com/guardian/janus/pull/4612).
> feat: create placeholder npm build step in CI

- app/aws/AuditTrailDB.scala
- app/controllers/Audit.scala
- app/controllers/Janus.scala
- app/logic/AuditTrail.scala
- test/aws/AuditTrailDBTest.scala
- test/logic/AuditTrailTest.scala
This change optimises and simplifies some of the code that manages interactions with the audit trail DB table.
1. Removal of redundant [calls to describe table](https://github.com/guardian/janus-app/blob/f522bca83d9d90657634b038c7734a9871974161/app/aws/AuditTrailDB.scala#L22-L25).
The name of the table and its key schema are already hardcoded throughout the code so it seems redundant to occasionally look these details up as well.
2. Removal of redundant table name parameter from various methods.
As mentioned above, the table name is already hardcoded so need to pass it around as a parameter.
3. Replaced an awkward tuple with a case class, as suggested in [this comment](https://github.com/guardian/janus-app/pull/500#discussion_r1944762210).
4. Replaced repeated use of string literal table …
> Refactor audit trail code

- app/aws/Federation.scala
- app/data/Policies.scala
- build.sbt
- configTools/src/main/scala/com/gu/janus/model/models.scala
- configTools/src/main/scala/com/gu/janus/policy/Iam.scala
- configTools/src/main/scala/com/gu/janus/policy/Statements.scala
- configTools/src/test/scala/com/gu/janus/policy/IamSpec.scala
- configTools/src/test/scala/com/gu/janus/policy/IamTest.scala
- configTools/src/test/scala/com/gu/janus/policy/StatementsTest.scala
- test/aws/FederationTest.scala
- test/fixtures/Fixtures.scala
- test/logic/UserAccessTest.scala
This change removes all dependence on [AWS v1 SDKs](https://github.com/aws/aws-sdk-java) and on the [archived awscala library](https://github.com/seratch/AWScala).
All interaction with AWS is now done through [v2 SDKs](https://github.com/aws/aws-sdk-java-v2/).
This will make the code more secure and easier to maintain.
AWS provides a [library for modelling IAM policies](https://mvnrepository.com/artifact/software.amazon.awssdk/iam-policy-builder) but to make use of this library would involve changing a lot of code in this repo and in the call sites of the [configTools library](https://github.com/guardian/janus-app/tree/fd3f01d5db3f2d407b168438da15d381988fa807/configTools/src), making the change history difficult to navigate.
Instead we have created case classes to model policies that …
> Upgrade AWS IAM v1 client to v2

- .github/workflows/trigger-private-janus-build.yml
- .nvmrc
Adds an `.nvmrc` file for the Node version and references this in the 'Install Node' step of the `trigger-private-janus-build` action. 
This follows from a [comment on the related Janus PR](https://github.com/guardian/janus/pull/4612#discussion_r1973545446), which will also reference the `.nvmrc` file.
> feat: use nvmrc file for node version

- app/views/audit.scala.html
- frontend/janus.js
There was a console error on the audit trail page about the submit functionality: `Uncaught TypeError: document.getElementById(...).on is not a function`.
The javascript code was calling an `.on('submit')` function for the button element. It turns out this functionality isn't required anyway, as the `<button>` element by default has the type of 'submit' and will submit the form without the need for javascript. 
I have removed the javascript and made the functionality of the button more explicit by specifying its parent form id and giving it the type of 'submit'.
No console error and datepicker continues to work as expected.
> fix: console error in audit page

- app/AppComponents.scala
- app/aws/Clients.scala
- app/conf/Config.scala
- build.sbt
- conf/application.conf
This change integrates [Play secret rotation](https://github.com/guardian/play-secret-rotation) into the app.  The secret is now read from SSM param store, rather than from a config file.  We aren't yet automatically rotating the secret - that is still a manual step for now.
Once this has been fully set up, we will have an automatically updated secret, which will safe us some toil and keep us secure.
Before this can be merged:
Co-authored-by: @tjsilver
> Read Play secret from param store

- example/build.sbt
- example/src/main/scala/com/example/Support.scala
- example/src/test/scala/com/example/SupportTest.scala
This change applies the migration from Joda time to java.time introduced in #525 to the example config-generating sub-project.
In the config generated by the project, timestamps now appear without nanoseconds, eg. `1970-01-06T10:00:00Z` instead of `1970-01-06T10:00:00.000Z`.  But as they are both ISO-8601 strings with UTC timezones and and we don't use non-zero nanoseconds anywhere, they are decoded identically whether as Joda `DateTime`s or as java.time `Instance`s.
> Bump config-tools dependency in example project

- app/AppComponents.scala
- app/conf/Config.scala
- app/controllers/Utility.scala
- app/logic/Owners.scala
- app/logic/ViewHelpers.scala
- app/views/accounts.scala.html
- configTools/src/main/scala/com/gu/janus/model/models.scala
- frontend/main.css
- test/conf/ConfigTest.scala
- test/logic/OwnersTest.scala
- test/logic/ViewHelpersTest.scala
This adds the account number to the accounts page, which is a critical piece of information for properly understanding which account is which.
This version of the page pulls the account number from the configured role, which is a nice simple way to go about it. A more complete solution would use the configured role to call `STS.getCallerIdentity` but this isn't currently required and would make this all more complicated.
We also tidy up and simplify the "owners" display. The previous implementation dates back to Janus' early versions, where there were only "devs" and "admins". This assumption no longer holds, so we instead list everyone that has any access, and tell users to look at the Janus access config to find out more detail.
Here again, a future version could show the JSON policy(s) …
> Update the accounts information page

- app/aws/Federation.scala
- app/data/Policies.scala
- configTools/src/main/scala/com/gu/janus/Validation.scala
- configTools/src/main/scala/com/gu/janus/config/Loader.scala
- configTools/src/main/scala/com/gu/janus/model/configuredRepresentation.scala
- configTools/src/main/scala/com/gu/janus/model/models.scala
- configTools/src/main/twirl/com/gu/janus/config/templates/janusData.scala.txt
- configTools/src/test/resources/example-without-permissions-repo.conf
- configTools/src/test/resources/example.conf
- configTools/src/test/scala/com/gu/janus/ValidationTest.scala
- configTools/src/test/scala/com/gu/janus/config/ConfigIntegrationTests.scala
- configTools/src/test/scala/com/gu/janus/config/LoaderTest.scala
- configTools/src/test/scala/com/gu/janus/config/WriterTest.scala
Adds support for managed policies in Janus permissions, alongside our typical inline policy document approach.
This is groundwork to unlock the ability to add support for a read-only permission in Janus. This addresses [a years-old request](https://github.com/guardian/janus/issues/2859) from Janus users, and has been requested by InfoSec.
We update the `Permission` model so that it can contain an inline policy (as now) and/or a list of managed policies ARNs, and provide some helpful (and clear) constructors for the new combinations. This involves updating the code that writes and loads Janus configuration files so that it supports these new permission definitions. We also update the actual `Federation.assumeRole` implementation, so that it provides the permission's policies whether they …
> Managed policy support

- .github/dependabot.yml
We currently have multiple dependabot PRs open to bump version updates in GitHub actions. This takes time, because the app needs to be rebuilt after each PR is merged. For patch and minor version bumps on GitHub provided acitons, we're probably ok to tackle them as a group.
> Group GitHub actions version bumps

- README.md
- project/RunClientHook.scala
- Adds information to the documentation outlining the addition of a Node frontend bundle.
- Updates the link to the `PlayRunHook` docs.
> docs: add info about Node bundle

- .scalafmt.conf
- README.md
- app/AppComponents.scala
- app/aws/PasskeyChallengeDB.scala
- app/aws/PasskeyDB.scala
- app/controllers/PasskeyController.scala
- app/logic/Passkey.scala
- app/models/Passkey.scala
- app/models/models.scala
- build.sbt
- conf/routes
- local-dev/README.md
- test/aws/PasskeyChallengeDBTest.scala
- test/aws/PasskeyDBTest.scala
- test/logic/PasskeyTest.scala
- version.sbt
This adds two new endpoints to enable registration of passkeys for a new authentication feature:
* GET /passkey/registration-options
* POST /passkey/register 
When the feature is complete it will improve the security of the app.
To test registration, it should be possible to hit these two endpoints in coordination with a browser that supports creation of passkey public key credentials, using the [navigator.credentials.create](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#creating_a_key_pair_and_registering_a_user) call.
The implementation uses the `webauthn4j` library and is heavily reliant on its excellent [docs](https://webauthn4j.github.io/webauthn4j/en/).  
The registration flow is described in detail there.
> feat: add routes for passkey registration

- README.md
- build.sbt
- local-dev/README.md
- project/DockerComposeHook.scala
Adds a play run hook that starts the DynamoDB via `docker compose`. This automates an essential manual step in getting this application running locally.
This saves a step that is a bit tedious, and that is hard to discover for users coming to janus-app for the first time.
> Add a play run hook that starts the DynamoDB container

- app/views/main.scala.html
- frontend/package.json
To enable https on the frontend app when running locally. 
Also removes the 'hot module reloading' option from parcel as this feature is currently not working. We can revisit this in the future.
We are able to run the app locally in Safari as well as Firefox and Chrome.
There is an associated PR in the [`janus` repo](https://github.com/guardian/janus/pull/4728) to create the nginx mapping.
> feat: enable https on the frontend app when running locally

- app/aws/Federation.scala
The configuration of privileges is slightly different in Prod and Dev environments.  This changes the username that can revoke access to accounts to reflect this difference.
We will be able to test revocation of all current access to an AWS account locally in a dev environment.
See guardian/janus#4737 for configuration of Guardian's resources for local testing.
> fix: update roleSessionName for account revocation

- app/controllers/PasskeyAuthFilter.scala
- app/controllers/PasskeyController.scala
- app/models/Passkey.scala
- app/models/models.scala
- frontend/passkeys.js
- test/logic/PasskeyTest.scala
We're using Circe for Json handling of the passkey responses largely because we were using it in the configTools subproject and then over-generalised.  It's easier to use Play-json in a Play app as it slightly simplifies the handling of json request bodies and gives us consistent handling of Json throughout the app.
As we're working in the Play framework it makes sense to use its features unless there's a reason not to.
> refactor: migrate from Circe to Play Json for passkey data encoding

- app/aws/PasskeyChallengeDB.scala
- app/aws/PasskeyDB.scala
- app/controllers/PasskeyAuthFilter.scala
- app/controllers/PasskeyController.scala
- app/logic/Passkey.scala
- app/models/models.scala
- app/views/userAccount.scala.html
- frontend/passkeys.js
- test/logic/PasskeyTest.scala
This adds a mechanism to the frontend to set a passkey name during the registration process.  The name is added to the data stored in the Dynamo passkeys table.  This change also uses the names to list passkeys on the user account page.
Users are allowed up to two passkeys so this change enables them to identify the passkeys they have already registered.  In the future it will allow them to choose which one to delete if they want to.
Co-authored-by: @tjsilver
> Add a user-defined passkey name to the passkey data

- app/aws/PasskeyDB.scala
- app/controllers/PasskeyController.scala
- app/models/Passkey.scala
- app/views/userAccount.scala.html
- frontend/passkeys.js
- test/logic/PasskeyTest.scala
It adds the time that a passkey was created and registered in Janus to the database and shows it in the UI.
We can see when a passkey was created and use this data for troubleshooting or for sorting and filtering.
See also #566
> feat: add registration timestamp to passkey data

- app/aws/PasskeyDB.scala
- app/controllers/PasskeyController.scala
- app/models/Passkey.scala
- app/views/userAccount.scala.html
This change adds the passkey's [AAGUID](https://web.dev/articles/webauthn-aaguid) (Authenticator Attestation Global Unique Identifier) to our passkey metadata model.
We can use the AAGUID to identify the type of authenticator that generated the passkey.
A further step is required to get the authenticator type from the AAGUID.  We need to look it up in a data feed that is published monthly by the [Fido Alliance](https://fidoalliance.org/metadata/).  The further step is described in [this Trello card](https://trello.com/c/22xJM3hH).
> feat: Add AAGUID to Passkey metadata

- app/aws/PasskeyDB.scala
- app/controllers/PasskeyAuthFilter.scala
- app/controllers/PasskeyController.scala
- app/models/Passkey.scala
- app/views/userAccount.scala.html
This adds a timestamp for the last time the passkey was used to authenticate an action to the database.
We then show the timestamp on the passkey section of the user account page.
Can be used for troubleshooting and to give user confidence.
> feat: Add lastUsedTime to Passkey model

- app/aws/PasskeyDB.scala
- app/controllers/PasskeyController.scala
- app/views/userAccount.scala.html
- conf/routes
- frontend/janus.js
- frontend/passkeys.js
This pull request introduces functionality for deleting passkeys, including backend, frontend, and UI changes. The most important changes include adding new methods for deleting passkeys in the database, creating a corresponding API endpoint, updating the UI to include delete buttons, and implementing frontend logic to handle passkey deletion.
* **Database Methods**: Added `loadCredentialByName` and `deleteById` methods to the `PasskeyDB` object to query and delete passkeys from the DynamoDB table. These methods handle exceptions and provide meaningful error messages.
* **Controller Endpoint**: Introduced a `deletePasskey` method in `PasskeyController` to handle HTTP requests for deleting passkeys. It validates the request, deletes the passkey using `PasskeyDB`, and redirects the user …
> feat: add delete passkey functionality

- app/controllers/PasskeyController.scala
- app/logic/Passkey.scala
- app/models/Passkey.scala
- test/logic/PasskeyTest.scala
Instead of using handwritten `play-json` encodings this change makes use of the Json annotations that have already been attached to the models of the `webauthn4j` library.
This is to avoid having to remember to update Json encodings whenever we use an extra field.  It also gives us more consistency in that we're now using the `webauthn4j` library to encode and to decode Json in web requests and responses.
This is to pave the way for adding `excludeCredentials` argument to our `PublicKeyCredentialCreationOptions`, which in turn will stop the possibility of registering duplicate and therefore redundant passkeys.
> refactor: Use webauthn library native JSON encodings

- app/controllers/PasskeyController.scala
- app/models/Passkey.scala
- test/logic/PasskeyTest.scala
This change ensures that the user ID is base64url encoded when it's presented to [PublicKeyCredential.parseCreationOptionsFromJSON](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/parseCreationOptionsFromJSON_static) in the browser.
Without this change, certain users whose names are encoded in a way that doesn't produce a base64url encoded string will be rejected in some browsers, at least Chrome.
We see error:
> Error during passkey registration: Error during passkey registration: EncodingError: Failed to execute 'parseCreationOptionsFromJSON' on 'PublicKeyCredential': 'user.id' contains invalid base64url data
> fix (passkeys): Add custom encoding for PublicKeyCredentialUserEntity

- app/views/userAccount.scala.html
I have reverted the two-passkey limit as this was not required.
I have also changed this PR remove the error messaging and fetch api use from this PR as I will use Play session flash messages rather than client-side toast messages in a separate PR.
> feat: Improve UX of user account page

- .gitignore
- app/views/passkeymock/awsAccounts.scala.html
- frontend/janus.js
- frontend/passkeys.js
This change makes the bypass of passkeys consistent with the use of passkeys so that protected links are now POSTs instead of GETs in both cases.
This fixes an error introduced in #585 where, if passkeys were being bypassed, the link would do a GET but there was no corresponding GET route available on the server.
We can now do the same thing with the live links so that they can be tested with and without passkey authentication.
> feat: Enable bypassing of passkey authentication for testing

- build.sbt
Excludes a transitive test dependency that we don't currently use.
Resolves a critical vulnerability alert: https://github.com/guardian/janus-app/security/dependabot/19
> fix: Exclude htmlunit dependency to resolve security vulnerability

- app/controllers/PasskeyController.scala
- app/views/userAccount.scala.html
- conf/routes
- frontend/passkeys.js
Follows: #588 
This pull request introduces several updates to the passkey deletion functionality, including improvements to the backend API, frontend integration, and routing. The changes enhance user experience by providing better error handling, JSON responses, and immediate redirection upon successful deletion.
* [`app/controllers/PasskeyController.scala`](diffhunk://#diff-c598597e1c4a7dcb243f4ea2669b34ac7af0ea330884fb9d08abc2e09e19f73fL146-R182): Refactored the `deletePasskey` method to accept a `passkeyId` as a parameter, retrieve passkey metadata for better success messages, and return a JSON response with success, message, and redirection details.
* [`conf/routes`](diffhunk://#diff-3668dd1c5d74e6d728b59d45112f57372248fbbcde03767f2fe38499aceef443L33-R33): Changed the HTTP method …
> feat: use DELETE method instead of POST for passkey deletion

- .github/workflows/trigger-private-janus-build.yml
Compile config-tools to Scala 2.13 and in Scala 3.
Now that we are publishing two versions of the config-tools library, we need to make sure that the project is always able to compile to both.
> chore: Cross-compile the config-tools project

- app/AppComponents.scala
- app/views/accounts.scala.html
- app/views/consoleUrl.scala.html
- app/views/credentials.scala.html
- app/views/error.scala.html
- app/views/main.scala.html
- app/views/noPermissions.scala.html
- app/views/permissionDenied.scala.html
- conf/application.conf
This is another attempt at #603 - to update config to improve content security policy (CSP) and resolve deprecated config warnings.
On that occasion it gave us error:
> Refused to load the script ... because it violates the following Content Security Policy directive: "script-src 'nonce-...' 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:"
The difference in this PR is that nonce attributes have been added to HTML script elements to enable scripts to be loaded in browser with reduced risk of XSS injection, following the [Play CSP filter documentation](https://www.playframework.com/documentation/3.0.x/CspFilter#Using-CSP-in-Page-Templates).
Will stop broken functionality in future upgrades of Play.
This should be a no-op change.
Reproduced problem seen in Production by …
> chore: Update deprecated Play config (Attempt 2)

- app/logic/Passkey.scala
- test/logic/PasskeyTest.scala
This pull request updates the `Passkey` config in `app/logic/Passkey.scala` to modify the handling of resident (discoverable) keys during authentication.  It now 'discourages' resident keys.
Passkeys can't be discovered at authentication time unless they're referenced in the pre-authentication options call, which keeps the choice of passkeys under the control of the Janus server.
See https://www.corbado.com/glossary/resident-key#resident-key-vs-non-resident-keys-whats-the-difference
Resident keys are designed to make the flow smoother when the user is unknown.
In our case, there's always an identifiable signed-in user and we know their credential IDs so we don't need to be able to 'discover' passkeys.
> feat(passkeys): Discourage discoverable passkeys

- app/views/userAccount.scala.html
- frontend/passkeys.js
- Based on #615.
- Improves the user experience for managing passkeys by introducing stricter validation for passkey names and enhancing the frontend logic to prevent duplicate names.
* [`frontend/passkeys.js`](diffhunk://#diff-157d328996ad7679d704789ae8346a8f08d8aa777aab1f412acc445879b352f8L302-R383): Implemented logic to check for duplicate passkey names by retrieving existing names from the DOM and validating against them. Added error messages for duplicate names and improved validation feedback for invalid inputs.
* [`app/views/userAccount.scala.html`](diffhunk://#diff-374d8384fc5549c89757384e7a301bd56c2701178a0ecda3457140b0b40cd9b0L40-R40): Added a `data-passkey-name` attribute to the table cell displaying passkey names, enabling the frontend to identify and validate existing passkey …
> feat: name validation UX tweaks

- app/views/userAccount.scala.html
- frontend/passkeys.js
Currently, if a user tries to access a protected link when they haven't registered a passkey they are left on the page with a 400 error.
In this PR, the user is redirected to the user-account page where they are encouraged to register a passkey.
This improves the UX by making it clear what's happening and nudging the user to take the right action.
> feat(passkeys): Redirect to user account page if no passkeys

- app/aws/PasskeyChallengeDB.scala
- app/controllers/PasskeyAuthFilter.scala
- app/controllers/PasskeyController.scala
- app/models/Passkey.scala
- test/aws/PasskeyChallengeDBTest.scala
This change introduces a new `PasskeyFlow` enum, which is to enable us to distinguish between passkey challenges that have been stored for an authentication flow and those that have been stored for a registration flow.
This will ensure that the right challenge is compared during the passkey verification process.
There are various scenarios where challenges can get confused.  But this becomes more of an issue when passkeys are used to authenticate passkey registration requests.
The change adds a new `flow` key attribute to items in the `PasskeyChallenge` Dynamo table.
The table configuration will need to be updated to reflect this change.
> refactor: Introduce PasskeyFlow enum

- app/AppComponents.scala
- app/controllers/Janus.scala
- app/controllers/PasskeyController.scala
- app/controllers/ResultHandler.scala
- conf/routes
This pull request refactors the handling of passkeys, introduces a new `ResultHandler` trait for standardised response handling and simplifies the `PasskeyController`. The changes improve code modularity and maintainability and reduce duplication and improve maintainability.
* [`app/AppComponents.scala`](diffhunk://#diff-6b72d7326232bd79ee27038565637854aa6c65208c0a563207fce9787b2ea647L95-R95): Renamed `passkeyAuthenticators` to `passkeyAuthenticatorMetadata` and passed it as a new dependency to the `Janus` controller. Removed its usage from the `PasskeyController`. [[1]](diffhunk://#diff-6b72d7326232bd79ee27038565637854aa6c65208c0a563207fce9787b2ea647L95-R95) [[2]](diffhunk://#diff-6b72d7326232bd79ee27038565637854aa6c65208c0a563207fce9787b2ea647L122-R123) …
> Refactor: Improvements to passkeys code

- frontend/passkeys.js
We were seeing warnings in the server log:
`Illegal header: Illegal 'content-type' header: Invalid input 'EOI', expected tchar, OWS or '/'`.
This is because `auth-options` requests were being sent from passkeys.js with a `null` content type header.
The root cause is that `fetchWithCsrf` is being called with `null` as the contentType argument.
The optional arguments of `fetchWithCsrf` are `contentType` and `body` so in this PR the argument list has been rearranged to put these at the end.
This makes calls clearer and avoids inadvertently sending `null` as the `content type` header.
> fix: Stop sending null content-type request headers

- app/filters/PasskeyAuthFilter.scala
Some small improvements to the structure of the PasskeyAuthFilter in the hope of making its structure clearer.
* Renamed the `doFilter` method to `authenticatePasskey` to better reflect its purpose and changed its return type from `Future[Option[Result]]` to `Try[Unit`. ([app/filters/PasskeyAuthFilter.scalaL50-R58](diffhunk://#diff-56318c3aec7a1b8611cd782eef98cf5988839932247265bcef39ccca538ead29L50-R58))
* Replaced the `extractAuthenticationData` method with `extractAuthDataFromRequest` for improved naming consistency and extracted the logic for parsing the request body into a new helper method, `extractRequestBody`.
* Added a new helper method `validateCredentialExists` to encapsulate the logic for checking credential existence and handling related errors.
* Adjusted logging statements …
> refactor: Improve clarity of passkey authentication filter

- app/controllers/PasskeyController.scala
- app/models/models.scala
- frontend/passkeys.js
This change adds a check that the user appears on the access list before allowing them to register a passkey.
If they aren't on the list, calls to `passkey/registration-options` and to `passkey/register` will fail with a 403.
The frontend code has been modified to respond to failure in registration-options to stop the flow as soon as possible.
It's an additional check to ensure the user should be able to register a passkey before they try.
> feat(passkeys): Check access before registering

- app/AppComponents.scala
- app/controllers/Janus.scala
- app/controllers/Utility.scala
- app/views/userAccount.scala.html
- conf/routes
- frontend/main.css
@tjsilver and @akash1810 have suggested we should introduce a more user-friendly way to opt in to the passkey authentication integration while it's being trialled.
This change provides new routes to opt in and out, and adds them to the user-account page for convenience.
This will avoid people forgetting how to opt in and out if they want to.
This assumes you know how to get to the user account page, which we should probably link to from the current log-out page eventually.
> feat(passkeys): Add opt-in/out routes

- app/views/main.scala.html
To navigate to the user account page when the user clicks on their name in the navigation. This used to log them out, but straight back in again. The icon on mobile has changed to indicate the change in functionality.
The user account page is where passkeys are managed, so linking to this from the user name makes sense.
It might be worth putting the icon on the page for all media sizes, not just mobile. Would be keen to hear thoughts.
We may be able to remove the logout functionality now altogether as it's largely redundant, but this can be done in a follow-up PR.
> feat(nav): change user name in nav to point to user account page

- .github/workflows/dependency-review.yml
This change will warn us in advance if we are potentially introducing a vulnerability to the main branch.
The workflow will fail if a high level vulnerability is being introduced.
Running as a separate workflow because it only makes sense to run when there are changes to a pull request.
If successful, could auto-add to other repos.
See ['Dependency Review' comment](https://github.com/guardian/janus-app/pull/666#issuecomment-3187517197) below for output.
> chore: Review dependencies before merging
